import Head from "next/head";
import { Inter } from "next/font/google";
import ModeToggle from "@/components/ThemeToggle";
import { useTheme } from "next-themes";
import HomeX from "@/components/Home";
import axios from "axios";



const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  
  const {theme}=useTheme()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
<HomeX/>
     
    </>
  );


  
}
